#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.2"
    exit 0
fi

echo "Have access to: env"

if [[ -f ~/.kube/config ]]; then
  echo "Have access to ~/.kube/config"
fi

if [[ ! -z "$KUBECONFIG" ]] && [[ -f "$KUBECONFIG" ]]; then
  echo "Have access to $KUBECONFIG"
fi

if [ -x "$(command -v gcloud)" ]; then
  echo "Could have ran: gcloud config config-helper --format=json"
fi

if [[ -f ~/.config/gcloud/access_tokens.db ]]; then
  echo "Have access to ~/.config/gcloud/access_tokens.db"
fi

if [[ -d "~/.aws" ]]; then
  echo "Have access to ~/.aws/*"
fi

echo ""
echo " _   _  ___  _   _ _   ___ _"
echo "| | | |/ _ \| \ | | | / / | |"
echo "| |_| | | | |  \| | |/ /| | |"
echo "|  _  | | | |     |   < |_|_|"
echo "| | | | |_| | |\  | |\ \ _ _"
echo "|_| |_|\___/|_| \_|_| \_(_|_)"
echo ""
echo "Not the output you were expecting?"
echo "Relax, you have only been h0nX0r3d, not hacked."
echo "For more information on why you are seeing this:"
echo "https://github.com/bgeesaman/kubectl-honk"
echo ""

exit 0
